services:
  app:
    build: ./app/
    image: event-planner-api:latest
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: MFDP_app
#  web:
#    build: ./web-proxy
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      - app
#      - db

  rabbitmq:
    image: rabbitmq:3.13.1-management
    hostname: rabbitmq
    restart: always
    env_file:
      - ./app/rabbitmq_workers/.env

    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=sa
    container_name: MFDP_db
volumes:
  postgres_data:

