[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["fastapi", "sqlmodel", "pydantic", "requests"]
known_first_party = ["app", "object_servise", "interaction_servise", "routes", "database"]
combine_as_imports = true
include_trailing_comma = true
multi_line_output = 3

[tool.flake8]
max-line-length = 88
exclude = [
    "__pycache__",
    ".venv",
    "build",
    "dist",
    "migrations",
    ".git",
]
