#name: Run Tests on Merge to Main
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres:13
#        env:
#          POSTGRES_USER: user
#          POSTGRES_PASSWORD: password
#          POSTGRES_DB: mfdp_db
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#      rabbitmq:
#        image: rabbitmq:3-management
#        ports:
#          - 5672:5672
#          - 15672:15672
#        options: >-
#          --health-cmd "rabbitmq-diagnostics -q ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.11
#
#    - name: Install dependencies
#      run: |
#        pip install --upgrade pip
#        pip install -r app/requirements.txt
#        pip install pytest
#
#    - name: Run tests
#      working-directory: ./app
#      run: pytest tests/ --disable-warnings --maxfail=1
